# Generated by Django 3.0.5 on 2020-04-05 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='av_request',
            name='status',
        ),
    ]
